apiVersion: v1
kind: Service
metadata:
  name: external-oidc-provider
  namespace: hyperauth
  labels:
    app: external-oidc-provider
  annotations:
#    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
#    traefik.ingress.kubernetes.io/service.sticky.cookie.name: hyperauth
#    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: external-oidc-provider
  type: ClusterIP   # ClusterIP or LoadBalancer or NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-oidc-provider
  namespace: hyperauth
  labels:
    app: external-oidc-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-oidc-provider
  template:
    metadata:
      labels:
        app: external-oidc-provider
    spec:
      volumes:
        - name: ssl
          secret:
            secretName: external-oidc-provider-https-secret
      containers:
        - name: hyperauth
          image: tmaxcloudck/external-oidc-provider:latest #latest
          env:
            - name: TZ
              value: Asia/Seoul
            - name: SERVER_URL  # Set Https Protocols
              value: "https://tmax.initech.com"
            - name: NLS_URL     # Set with Https Protocols
              value: "https://demo.initech.com"
            - name: NLS_PORT
              value: "13443"
            - name: NLS_LOGIN_URN
              value: "/nls3/clientLogin.jsp"
            - name: NLS_LOGOUT_URN
              value: "/nls3/NCLogout.jsp"
            - name: ND_URL1     # Set Https Protocols
              value: "https://demo.initech.com:13443/rpc2"
            - name: ND_URL2     # Set Https Protocols
              value: "https://ndtest.initech.com:5481"
            - name: SSO_DOMAIN     # Set Https Protocols
              value: ".initech.com"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: ssl
              mountPath: /etc/x509/https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-oidc-provider
  namespace: hyperauth
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName : tmax-cloud
  tls:
    - hosts:  # Set Domain Name
        - tmax.initech.com
      secretName: external-oidc-provider-https-secret
  rules:  # Set Domain Name
    - host: tmax.initech.com
      http:
        paths:
          - backend:
              serviceName: external-oidc-provider
              servicePort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-oidc-provider-certificate
  namespace: hyperauth
spec:
  secretName: external-oidc-provider-https-secret
  duration: 8760h # 360d=1y
  renewBefore: 720h # 30d
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  #  ipAddresses:
  #    - 192.168.9.12
  dnsNames:
    # Set Domain Name
    - tmax.initech.com
    - tmax-cloud
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
